name: PDF Generator

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  
permissions:
  contents: write
  
jobs:
  generate_pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install patched wkhtmltopdf version
      - name: Install patched wkhtmltopdf
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq xfonts-75dpi
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo apt install -y ./wkhtmltox_0.12.6-1.bionic_amd64.deb

      # Step 3: Ensure that the input file exists
      - name: Ensure input file exists
        run: |
          if [ ! -f "./source.txt" ]; then
            echo "Input file not found! Exiting."
            exit 1
          fi

      # Step 4: Execute wkhtmltopdf commands with delay and error reporting
      - name: Execute wkhtmltopdf commands with delay and error handling
        run: |
          i=0
          while read line; do
            # Enhanced wkhtmltopdf command with error handling
            if ! bash -c "(echo _______ For line $((++i)) _____; wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line 2>&1 | tee -a ./report)"; then
              echo "Error occurred: Rerun \"wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line\" " >> ./report
            fi
            sleep $(shuf -i 3-8 -n 1)
          done < ./source.txt

      # Step 5: Configure git for committing changes
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit and push the report and any generated files
      - name: Commit and push changes
        run: |
          git add report *.pdf
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Add generated PDFs and report from GitHub Action"
            git push origin main
          fi
